apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fioolrk1o-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fioolrk1o-dotnet-basic-gitops